#!/usr/bin/env bash
python SpecialPreUpgrade.py
python VCActivityRemapper.py
python ManualUpgrade1.py
python Repackager2.py
python ManualUpgrade3.py
python UpgradeUnsafe4.py
python ManualUpgrade5.py
python LifecycleUpgrade6.py